### ISSUE TITLE
Client side code crashing the server outside the test env.

### ISSUE THREAD

**Issue by DeadSix27** [desht/pnc-repressurized#1]
Person of reddit here :)

Promised log: https://gist.github.com/DeadSix27/43b04bdf93310ff5803fcd09c3756d7b

Tested inside my test-pack as I wanted to start making quest lines for the mod to be ready.

**Comment by desht** [comment]
Yep, I was loading an event handler for a client-only class on both sides. Oops.

**Comment by desht** [comment]
Just pushed a commit which should fix the problem, but I haven't tested it on a dedicated server yet.  I'll try to get some testing done tomorrow.  Let me know if you get a chance to try it out...

**Comment by DeadSix27** [comment]
@desht Now crashes on ModuleSafetyValve.java:13 -> https://gist.github.com/DeadSix27/bc12f3578bb0ae8689fbd79d099521a5

**Comment by desht** [comment]
OK, I did a fair bit of refactoring, and I've also tested it - the mod now loads in a dedicated server, and I can connect to it OK.  Haven't tested everything, but I placed a few blocks down and so far so good.

Let me know how it goes.  And thanks for the (pre) alpha testing :)

**Comment by DeadSix27** [comment]
@desht Works fine so far :) Have not encountered any crashes or errors, but I didn't test everything of course.

**Comment by DeadSix27** [comment]
@desht 
Actually, the tablet errors out, but you listed it as not tested so thats probably why, but I can save you the first test I guess, here is the server-side error it causes:
https://gist.github.com/DeadSix27/fb34df66d10cd2cc4a6726586bf19a22

**Comment by desht** [comment]
Yeah, I have even looked at the tablet yet.  Getting drones hopefully sorted 100% this week, I'll look at the tablet as the next major feature.

**Comment by desht** [comment]
Just pushed some Amadron fixes - tablet should be working pretty well now

**Comment by DeadSix27** [comment]
@desht I'll check it out later :)
