### ISSUE TITLE
Fix rendering for UV light box

### ISSUE THREAD

**Issue by desht** [desht/pnc-repressurized#19]
Need a TESR for this, but we can probably limit TESR drawing to only when the lightbox has an item in it.  Possibly redo the static OBJ model with JSON.

Also, look at Albedo or Mirage for having the lightbox emit cool purple-coloured light while active.

**Comment by desht** [comment]
All done.

**Comment by darthvader45** [comment]
Sorry to reopen this, but the most recent build on Curseforge seems to have a problem with the UV light box render, as when it has a pcb in it, it only renders the white stripes (which I assume are the lights).  Looks really odd.

**Comment by desht** [comment]
Exact version number please?  Along with the version of Forge you're using.

**Comment by desht** [comment]
(By the way, I'm not seeing this problem at all on 1.12.2 or 1.14.4, so I suspect something's up with your instance).

**Comment by darthvader45** [comment]
Pneumaticcraft for 1.12.2: 0.11.14.395
Forge: 14.23.5.2847

**Comment by desht** [comment]
Yeah, sorry, doesn't happen for me at all on this version.

**Comment by darthvader45** [comment]
Weird.  I'm not even running Optifine, so I can effectively rule that out.  I'll delete the optifine config too, just to be sure.

**Comment by darthvader45** [comment]
Okay, I think I may have figured out the potential culprit.  Try testing with the version of Pneumaticcraft I reported and the most recent CF build of AtomicStryker's Dynamic Lights.  Afaik the UV light box emits a light, and that might have been picked up by Dynamic Lights, which would likely be why it messes up.
