### ISSUE TITLE
Remove what's left of the NotEnoughKeys integration

### ISSUE THREAD

**Issue by KamranMackey** [desht/pnc-repressurized#24]
NotEnoughKeys hasn't been maintained since the Minecraft 1.8 days, and as such I think the integration should be removed from the code. I don't think it's worth it to leave what's left of the integration in the code since NEK is pretty much dead.

**Comment by DeadSix27** [comment]
Yes, it got replaced by https://minecraft.curseforge.com/projects/controlling (in terms of community adaption)

And since that needs no integration

**Comment by desht** [comment]
Yep, I'm on board with that :)

**Comment by desht** [comment]
NEK code has been removed in this build.
