### ISSUE TITLE
API needs a little refactoring

### ISSUE THREAD

**Issue by desht** [desht/pnc-repressurized#27]
* Remove any references to non-API packages which are made from API code
* Move API from `src/main/java/me/desht/pneumaticcraft/api` to `src/api/java/me/desht/pneumaticcraft/api` - separate module
* This will allow easy creation of a separate API JAR, which can then be uploaded to a Maven repo somewhere (cloudpackage.io maybe?)

**Comment by DeadSix27** [comment]
Is https://files.minecraftforge.net/maven open to be used somehow? (AE2 uses it apparently)

**Comment by desht** [comment]
Not sure TBH.  Maybe I'll ask in the Forge forums.

It's not overly important though; there are plenty places where the JARs could be hosted for Maven purposes (including here on GitHub).

**Comment by DeadSix27** [comment]
@desht True, just seemed like a nice option if it's usable by the public somehow

**Comment by desht** [comment]
Closing this, with thanks to Zixxl.
