### ISSUE TITLE
compatibility with applied energistics' tiny TNT

### ISSUE THREAD

**Issue by Xiaminou** [desht/pnc-repressurized#42]
It appears that AE's Tiny TNT is not compatible with PNCR's way of making Compressed Iron as it destroys the Iron instead.
I liked using Tiny TNT back in 1.7.10 to start Pneumaticcraft because of the smaller explosion. Would it be possible to add it back?

**Comment by desht** [comment]
Yeah, I'll take a look at that.  Tiny TNT should work, so it's a bug that it doesn't.

**Comment by desht** [comment]
I wonder: could you check if you have tiny TNT block damage disabled in your AE2 config?

**Comment by Xiaminou** [comment]
It is enabled, it did damage the blocks.
If you can't find what's wrong, I also have Environmental Creepers installed, I know it can change explosions and block damage.
Maybe it's worth testing with just AE+PNC:R.

**Comment by desht** [comment]
Just did some testing, and ``ExplosionEvent.Detonate`` doesn't get fired when Tiny TNT explodes (it does get fired when regular TNT explodes, and when creepers explode).  If it worked in 1.7.10, that sounds like something's changed in AE2.  It would be worth asking them about that.
