### ISSUE TITLE
Amadron are thieves!

### ISSUE THREAD

**Issue by Xiaminou** [desht/pnc-repressurized#44]
I haven't used this in a long time so maybe I missed a step.
When using the amadron tablet the drone comes to pick up my emeralds but never delivers what I order.
Video for clarification: https://youtu.be/j084AvqK5ts

**Comment by desht** [comment]
Yeah, this may need some more testing. Also, can you check if you have any errors in the log file?

**Comment by Xiaminou** [comment]
No errors as far as I can see.
I'm just getting into the mod now that I've figured out a decent setup so expect more bug reports.

**Comment by Xiaminou** [comment]
By the way I tried to build the latest PNC:R from the source and got this
`* What went wrong:
Could not resolve all dependencies for configuration ':apiCompileClasspath'.
> Could not resolve igwmod:IGW-Mod-1.12.2:1.4.1-9.
  Required by:
      me.desht.pneumaticcraft:pnc-repressurized-master:1.12.2-0.1.0
   > Could not resolve igwmod:IGW-Mod-1.12.2:1.4.1-9.
      > Could not get resource 'https://modmaven.k-4u.nl/igwmod/IGW-Mod-1.12.2/1.4.1-9/IGW-Mod-1.12.2-1.4.1-9.pom'.
         > Could not GET 'https://modmaven.k-4u.nl/igwmod/IGW-Mod-1.12.2/1.4.1-9/IGW-Mod-1.12.2-1.4.1-9.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`

**Comment by desht** [comment]
Yeah, IGW version got bumped around the same time, up to 1.4.1-10.

**Comment by desht** [comment]
Amadron problem looks like a pathfinding issue with the emerald collection drone.  It heads back up to its despawn point and sits there confused not realising it should be despawning.
