### ISSUE TITLE
Assembly IO Unit give items to each other

### ISSUE THREAD

**Issue by Xiaminou** [desht/pnc-repressurized#48]
When using the Assembly IO Unit with a diagonal output chest the output IO Unit will give the output to the input IO Unit instead.
Video: https://youtu.be/uOSKwHze9_M

**Comment by Zixxl** [comment]
Seems like there is no check if the drop off location is another IO Unit.

Maybe `if (te instanceof TileEntityAssemblyRobot) return -1;` in method `TileEntityAssemblyIOUnit#getInventoryPlaceLocation(ItemStack, TileEntity)` could fix this.
