### ISSUE TITLE
In-game documentation

### ISSUE THREAD

**Issue by desht** [desht/pnc-repressurized#6]
IGW (in-game wiki) is not ported to 1.12 and I'm not very inclined to port it.

McJty's upcoming Lector mod may be a good solution here.

https://www.reddit.com/r/feedthebeast/comments/76zrsa/conclusion_on_the_manual_refactor/

**Comment by Xiaminou** [comment]
Now that IGW is ported to 1.12.2 is it not as simple as copying the pages from the 1.7.10 Pneumaticcraft version? For the old stuff at least.

**Comment by desht** [comment]
Actually, IGW support is already in. Wasn't quite as simple as copying the data files due to Mojang lowercasing requirements, but it's pretty much working.

**Comment by Xiaminou** [comment]
Oh good, guess I need to update my PNC:R then.

**Comment by desht** [comment]
Yep, it's changing very fast right  now :)
